name: python-news-crawler
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.13 # https://pyreadiness.org/3.9/
  - pip=22.1.2 # https://pip.pypa.io/en/stable/news/
  - pandas=1.5.1
  - pydantic 2.0
  - pip:
      # Define pip packages here -> https://pypi.org/
      - rpaframework==22.5.2 # https://rpaframework.org/releasenotes.html

